print("integer")
print(6)
print("\n")
print("float")
print(18.55)
print("\n")
print("complex")
print(5+10j)
print("\n")
print("string")
print("hola")
print("\n")
print("boolean")
print(False)
print("\n")
print("list")
print([1,2,3,4,5,6])
print("\n")
print("tuple")
print((9.55,8.5,6.8))
print("\n")
print("set")
print({9.55,8.5,6.8})
print("\n")
print("dictionary")
print({'nombre':'luis'})

#3
import math
x1, y1 = 2, 3
x2, y2 = 10, 8
slope_2 = ((y2-y1)/(x2-x1))
distance = math.sqrt((x2-x1)**2+(y2-y1)**2)
